name: Update renv.lock create PR and Jira Issue                
on:
  schedule:
    - cron: '0 0/5 * * 0' # Runs weekly, you can adjust the schedule
  workflow_dispatch:
jobs:
  update-renv-lock:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: install linux dependencies
      run: sudo apt-get install libcurl4-openssl-dev libfribidi-dev libharfbuzz-dev libfreetype6-dev libgdal-dev libudunits2-dev
    
    - name: Install dependencies
      shell: Rscript {0}
      run: |
        install.packages("renv")
        # renv::install()
        renv::install("rlang")
        renv::install("lifecycle")
        renv::install("vctrs")
        renv::install("pillar")
        # renv::restore()

    - name: Update renv.lock
      shell: Rscript {0}
      run: |
        renv::update()
        renv::snapshot()
    # - name: check renv.lock changes
    #   run: git diff renv.lock

    - name: Commit and push changes to feature branch
      run: |
        git config user.name 'ImKarthikSelvam'
        git config user.email 'karthiksksamy@gmail.com'
        git checkout -b create-renv-lock-file
        git add renv.lock
        git commit -m 'create renv.lock file'
        git push --set-upstream origin create-renv-lock-file
      env:
        GITHUB_TOKEN: ${{ secrets.DEPENDABOT_GITHUB_TOKEN}}