name: Update renv.lock create PR and Jira Issue                
on:
  schedule:
    - cron: '0 0/5 * * 0' # Runs weekly, you can adjust the schedule
  workflow_dispatch:

env:
  JIRA_BASE_URL: https://karthiksksamy.atlassian.net/
  JIRA_USER_EMAIL: karthiksksamy@gmail.com
  JIRA_API_TOKEN: ${{secrets.JIRA_API_TOKEN}}
  JIRA_PROJECT: KAN
  JIRA_ISSUE_TYPE: Task

jobs:
  update-renv-lock:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: install linux dependencies
      run: sudo apt-get install libcurl4-openssl-dev libfribidi-dev libharfbuzz-dev libfreetype6-dev libgdal-dev libudunits2-dev
    
    - name: Install dependencies
      shell: Rscript {0}
      run: |
        install.packages("renv")
        # renv::install()
        renv::install("rlang")
        renv::install("lifecycle")
        renv::install("vctrs")
        renv::install("pillar")
        # renv::restore()

    - name: Update renv.lock
      shell: Rscript {0}
      run: |
        renv::update()
        renv::snapshot()

    - name: check renv.lock changes
      run: git diff renv.lock

    - name: Create pull request
      id: cpr
      uses: peter-evans/create-pull-request@v6
      with:
        GITHUB_TOKEN: ${{ secrets.DEPENDABOT_GITHUB_TOKEN}}
        commit-message: Update renv.lock file
        title: 'Update renv.lock file'
        body: 'This PR updates the renv.lock file of repo'
        branch: create-renv-lock-file

    - name: Login to Jira
      uses: atlassian/gajira-login@v2.0.0
      env:
        JIRA_BASE_URL: ${{env.JIRA_BASE_URL}}
        JIRA_USER_EMAIL: ${{env.JIRA_USER_EMAIL}}
        JIRA_API_TOKEN: ${{secrets.JIRA_API_TOKEN}}

    - name: Create Jira Issue
      id: create
      uses: atlassian/gajira-create@v2.0.1
      with:
        project: ${{env.JIRA_PROJECT}}
        issuetype: ${{env.JIRA_ISSUE_TYPE}}
        summary: |
          [${{ steps.cpr.outputs.pull-request-branch }}] Update renv.lock file
        description: |
          ${{ steps.cpr.outputs.pull-request-url }}

    - name: Update PR Title with Jira Issue
      run: |
        NEW_TITLE="${{ steps.create.outputs.issue }} - Update renv.lock file"
        gh pr edit ${{ steps.cpr.outputs.pull-request-number }} --title "$NEW_TITLE" --body "test"
      env:
        GITHUB_TOKEN: ${{ secrets.DEPENDABOT_GITHUB_TOKEN}}

    - name: jira-labels-sync-action
      uses: nicoandresr/jira-labels-sync-action@v1.0.0
      with:
        github-token: ${{ secrets.DEPENDABOT_GITHUB_TOKEN }}
        jira-token: ${{ secrets.JIRA_API_TOKEN }}
        jira-base-url: ${{env.JIRA_BASE_URL}}
        jira-project-key: ${{env.JIRA_PROJECT}}
        labels: '{"r_dependency": "r_dependency"}'